import os
import glob

Import('env')

# env.CppUnitTest('money_test2', ['money_test2.cpp'])

files = glob.glob('*_test.cpp')
for file in files:
  t = env.Program(target='../bin/' + file[:-4], source=[file], LIBS=env['libs'])
